/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAjustesRouteImport } from './routes/_app.ajustes'
import { Route as AppLancamentosRouteImport } from './routes/_app.lancamentos'
import { Route as AppOrcamentoRouteImport } from './routes/_app.orcamento'
import { Route as AppAjustesIndexRouteImport } from './routes/_app.ajustes.index'
import { Route as AppAjustesAplicativoRouteImport } from './routes/_app.ajustes.aplicativo'
import { Route as AppAjustesCategoriasRouteImport } from './routes/_app.ajustes.categorias'
import { Route as AppAjustesChavesApiRouteImport } from './routes/_app.ajustes.chaves-api'
import { Route as AppAjustesContasRouteImport } from './routes/_app.ajustes.contas'
import { Route as AppAjustesGrupoRouteImport } from './routes/_app.ajustes.grupo'
import { Route as AppAjustesPerfilRouteImport } from './routes/_app.ajustes.perfil'
import { Route as AppConviteIdRouteImport } from './routes/_app.convite.$id'
import { Route as AppRelatoriosIndexRouteImport } from './routes/_app.relatorios.index'
import { Route as AppRelatoriosSlugRouteImport } from './routes/_app.relatorios.$slug'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesRoute = AppAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AppRoute,
} as any)
const AppLancamentosRoute = AppLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppAjustesIndexRoute = AppAjustesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesAplicativoRoute = AppAjustesAplicativoRouteImport.update({
  id: '/aplicativo',
  path: '/aplicativo',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesCategoriasRoute = AppAjustesCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesChavesApiRoute = AppAjustesChavesApiRouteImport.update({
  id: '/chaves-api',
  path: '/chaves-api',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesContasRoute = AppAjustesContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesGrupoRoute = AppAjustesGrupoRouteImport.update({
  id: '/grupo',
  path: '/grupo',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppAjustesPerfilRoute = AppAjustesPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppAjustesRoute,
} as any)
const AppConviteIdRoute = AppConviteIdRouteImport.update({
  id: '/convite/$id',
  path: '/convite/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosIndexRoute = AppRelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosSlugRoute = AppRelatoriosSlugRouteImport.update({
  id: '/relatorios/$slug',
  path: '/relatorios/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/entrar': typeof EntrarRoute
  '/ajustes': typeof AppAjustesRouteWithChildren
  '/lancamentos': typeof AppLancamentosRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/ajustes/aplicativo': typeof AppAjustesAplicativoRoute
  '/ajustes/categorias': typeof AppAjustesCategoriasRoute
  '/ajustes/chaves-api': typeof AppAjustesChavesApiRoute
  '/ajustes/contas': typeof AppAjustesContasRoute
  '/ajustes/grupo': typeof AppAjustesGrupoRoute
  '/ajustes/perfil': typeof AppAjustesPerfilRoute
  '/convite/$id': typeof AppConviteIdRoute
  '/relatorios/$slug': typeof AppRelatoriosSlugRoute
  '/ajustes/': typeof AppAjustesIndexRoute
  '/relatorios/': typeof AppRelatoriosIndexRoute
}
export interface FileRoutesByTo {
  '/entrar': typeof EntrarRoute
  '/lancamentos': typeof AppLancamentosRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/': typeof AppIndexRoute
  '/ajustes/aplicativo': typeof AppAjustesAplicativoRoute
  '/ajustes/categorias': typeof AppAjustesCategoriasRoute
  '/ajustes/chaves-api': typeof AppAjustesChavesApiRoute
  '/ajustes/contas': typeof AppAjustesContasRoute
  '/ajustes/grupo': typeof AppAjustesGrupoRoute
  '/ajustes/perfil': typeof AppAjustesPerfilRoute
  '/convite/$id': typeof AppConviteIdRoute
  '/relatorios/$slug': typeof AppRelatoriosSlugRoute
  '/ajustes': typeof AppAjustesIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_app/ajustes': typeof AppAjustesRouteWithChildren
  '/_app/lancamentos': typeof AppLancamentosRoute
  '/_app/orcamento': typeof AppOrcamentoRoute
  '/_app/': typeof AppIndexRoute
  '/_app/ajustes/aplicativo': typeof AppAjustesAplicativoRoute
  '/_app/ajustes/categorias': typeof AppAjustesCategoriasRoute
  '/_app/ajustes/chaves-api': typeof AppAjustesChavesApiRoute
  '/_app/ajustes/contas': typeof AppAjustesContasRoute
  '/_app/ajustes/grupo': typeof AppAjustesGrupoRoute
  '/_app/ajustes/perfil': typeof AppAjustesPerfilRoute
  '/_app/convite/$id': typeof AppConviteIdRoute
  '/_app/relatorios/$slug': typeof AppRelatoriosSlugRoute
  '/_app/ajustes/': typeof AppAjustesIndexRoute
  '/_app/relatorios/': typeof AppRelatoriosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/ajustes'
    | '/lancamentos'
    | '/orcamento'
    | '/ajustes/aplicativo'
    | '/ajustes/categorias'
    | '/ajustes/chaves-api'
    | '/ajustes/contas'
    | '/ajustes/grupo'
    | '/ajustes/perfil'
    | '/convite/$id'
    | '/relatorios/$slug'
    | '/ajustes/'
    | '/relatorios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/entrar'
    | '/lancamentos'
    | '/orcamento'
    | '/'
    | '/ajustes/aplicativo'
    | '/ajustes/categorias'
    | '/ajustes/chaves-api'
    | '/ajustes/contas'
    | '/ajustes/grupo'
    | '/ajustes/perfil'
    | '/convite/$id'
    | '/relatorios/$slug'
    | '/ajustes'
    | '/relatorios'
  id:
    | '__root__'
    | '/_app'
    | '/entrar'
    | '/_app/ajustes'
    | '/_app/lancamentos'
    | '/_app/orcamento'
    | '/_app/'
    | '/_app/ajustes/aplicativo'
    | '/_app/ajustes/categorias'
    | '/_app/ajustes/chaves-api'
    | '/_app/ajustes/contas'
    | '/_app/ajustes/grupo'
    | '/_app/ajustes/perfil'
    | '/_app/convite/$id'
    | '/_app/relatorios/$slug'
    | '/_app/ajustes/'
    | '/_app/relatorios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes': {
      id: '/_app/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lancamentos': {
      id: '/_app/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof AppLancamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamento': {
      id: '/_app/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ajustes/': {
      id: '/_app/ajustes/'
      path: '/'
      fullPath: '/ajustes/'
      preLoaderRoute: typeof AppAjustesIndexRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/aplicativo': {
      id: '/_app/ajustes/aplicativo'
      path: '/aplicativo'
      fullPath: '/ajustes/aplicativo'
      preLoaderRoute: typeof AppAjustesAplicativoRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/categorias': {
      id: '/_app/ajustes/categorias'
      path: '/categorias'
      fullPath: '/ajustes/categorias'
      preLoaderRoute: typeof AppAjustesCategoriasRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/chaves-api': {
      id: '/_app/ajustes/chaves-api'
      path: '/chaves-api'
      fullPath: '/ajustes/chaves-api'
      preLoaderRoute: typeof AppAjustesChavesApiRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/contas': {
      id: '/_app/ajustes/contas'
      path: '/contas'
      fullPath: '/ajustes/contas'
      preLoaderRoute: typeof AppAjustesContasRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/grupo': {
      id: '/_app/ajustes/grupo'
      path: '/grupo'
      fullPath: '/ajustes/grupo'
      preLoaderRoute: typeof AppAjustesGrupoRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/ajustes/perfil': {
      id: '/_app/ajustes/perfil'
      path: '/perfil'
      fullPath: '/ajustes/perfil'
      preLoaderRoute: typeof AppAjustesPerfilRouteImport
      parentRoute: typeof AppAjustesRoute
    }
    '/_app/convite/$id': {
      id: '/_app/convite/$id'
      path: '/convite/$id'
      fullPath: '/convite/$id'
      preLoaderRoute: typeof AppConviteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios/': {
      id: '/_app/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AppRelatoriosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios/$slug': {
      id: '/_app/relatorios/$slug'
      path: '/relatorios/$slug'
      fullPath: '/relatorios/$slug'
      preLoaderRoute: typeof AppRelatoriosSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAjustesRouteChildren {
  AppAjustesAplicativoRoute: typeof AppAjustesAplicativoRoute
  AppAjustesCategoriasRoute: typeof AppAjustesCategoriasRoute
  AppAjustesChavesApiRoute: typeof AppAjustesChavesApiRoute
  AppAjustesContasRoute: typeof AppAjustesContasRoute
  AppAjustesGrupoRoute: typeof AppAjustesGrupoRoute
  AppAjustesPerfilRoute: typeof AppAjustesPerfilRoute
  AppAjustesIndexRoute: typeof AppAjustesIndexRoute
}

const AppAjustesRouteChildren: AppAjustesRouteChildren = {
  AppAjustesAplicativoRoute: AppAjustesAplicativoRoute,
  AppAjustesCategoriasRoute: AppAjustesCategoriasRoute,
  AppAjustesChavesApiRoute: AppAjustesChavesApiRoute,
  AppAjustesContasRoute: AppAjustesContasRoute,
  AppAjustesGrupoRoute: AppAjustesGrupoRoute,
  AppAjustesPerfilRoute: AppAjustesPerfilRoute,
  AppAjustesIndexRoute: AppAjustesIndexRoute,
}

const AppAjustesRouteWithChildren = AppAjustesRoute._addFileChildren(
  AppAjustesRouteChildren,
)

interface AppRouteChildren {
  AppAjustesRoute: typeof AppAjustesRouteWithChildren
  AppLancamentosRoute: typeof AppLancamentosRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConviteIdRoute: typeof AppConviteIdRoute
  AppRelatoriosSlugRoute: typeof AppRelatoriosSlugRoute
  AppRelatoriosIndexRoute: typeof AppRelatoriosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAjustesRoute: AppAjustesRouteWithChildren,
  AppLancamentosRoute: AppLancamentosRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppIndexRoute: AppIndexRoute,
  AppConviteIdRoute: AppConviteIdRoute,
  AppRelatoriosSlugRoute: AppRelatoriosSlugRoute,
  AppRelatoriosIndexRoute: AppRelatoriosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
