import type { CategoryIconName } from '@bolso/shared'
import {
  Accessibility,
  Activity,
  Ambulance,
  Apple,
  Armchair,
  Baby,
  Backpack,
  Bandage,
  Banknote,
  Bath,
  Bed,
  BedSingle,
  Beer,
  Bell,
  Bike,
  Blinds,
  Blocks,
  Bone,
  Book,
  Bookmark,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Bus,
  BusFront,
  CakeSlice,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Car,
  CarFront,
  Carrot,
  CarTaxiFront,
  Cat,
  ChartLine,
  ChartPie,
  Church,
  Cigarette,
  CircleParking,
  Clock,
  Cloud,
  Coffee,
  Coins,
  CookingPot,
  CreditCard,
  Croissant,
  Cross,
  Dices,
  Dog,
  DollarSign,
  DoorOpen,
  Drama,
  Droplet,
  Drumstick,
  Dumbbell,
  Egg,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HandCoins,
  HandHeart,
  Handshake,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hospital,
  House,
  IceCreamCone,
  IdCard,
  Joystick,
  Key,
  Lamp,
  Landmark,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  type LucideIcon,
  Luggage,
  Mail,
  MapPin,
  Mars,
  Medal,
  Microwave,
  Milk,
  Monitor,
  MountainSnow,
  Music,
  Navigation,
  Package,
  PaintRoller,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PencilRuler,
  Percent,
  PersonStanding,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  Receipt,
  Recycle,
  Refrigerator,
  Rocket,
  Router,
  Ruler,
  Salad,
  Sandwich,
  Scale,
  School,
  Scissors,
  Send,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Smile,
  Sofa,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sticker,
  Store,
  Sun,
  Syringe,
  Tag,
  Tags,
  Target,
  Tent,
  Ticket,
  ToyBrick,
  TrainFront,
  Trash2,
  TreePalm,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Venus,
  Volleyball,
  Wallet,
  WashingMachine,
  Waves,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'

// O Record obriga a ter um ícone para cada nome listado no shared
export const categoryIcons: Record<CategoryIconName, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  store: Store,
  utensils: Utensils,
  'cooking-pot': CookingPot,
  salad: Salad,
  pizza: Pizza,
  sandwich: Sandwich,
  drumstick: Drumstick,
  fish: Fish,
  egg: Egg,
  milk: Milk,
  apple: Apple,
  carrot: Carrot,
  croissant: Croissant,
  'cake-slice': CakeSlice,
  candy: Candy,
  'ice-cream-cone': IceCreamCone,
  popcorn: Popcorn,
  coffee: Coffee,
  beer: Beer,
  wine: Wine,
  house: House,
  bed: Bed,
  sofa: Sofa,
  armchair: Armchair,
  lamp: Lamp,
  blinds: Blinds,
  bath: Bath,
  'shower-head': ShowerHead,
  'washing-machine': WashingMachine,
  refrigerator: Refrigerator,
  microwave: Microwave,
  plug: Plug,
  wrench: Wrench,
  hammer: Hammer,
  'paint-roller': PaintRoller,
  key: Key,
  'door-open': DoorOpen,
  'trash-2': Trash2,
  package: Package,
  zap: Zap,
  droplet: Droplet,
  flame: Flame,
  wifi: Wifi,
  phone: Phone,
  smartphone: Smartphone,
  router: Router,
  tv: Tv,
  monitor: Monitor,
  printer: Printer,
  receipt: Receipt,
  'file-text': FileText,
  recycle: Recycle,
  shield: Shield,
  cloud: Cloud,
  globe: Globe,
  car: Car,
  'car-front': CarFront,
  'car-taxi-front': CarTaxiFront,
  fuel: Fuel,
  'circle-parking': CircleParking,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  truck: Truck,
  plane: Plane,
  ship: Ship,
  luggage: Luggage,
  'map-pin': MapPin,
  navigation: Navigation,
  footprints: Footprints,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  bandage: Bandage,
  hospital: Hospital,
  ambulance: Ambulance,
  cross: Cross,
  glasses: Glasses,
  brain: Brain,
  accessibility: Accessibility,
  dumbbell: Dumbbell,
  activity: Activity,
  'graduation-cap': GraduationCap,
  book: Book,
  'book-open': BookOpen,
  library: Library,
  school: School,
  backpack: Backpack,
  'bus-front': BusFront,
  'pencil-ruler': PencilRuler,
  pencil: Pencil,
  ruler: Ruler,
  briefcase: Briefcase,
  laptop: Laptop,
  presentation: Presentation,
  'building-2': Building2,
  users: Users,
  'user-round': UserRound,
  handshake: Handshake,
  'id-card': IdCard,
  scale: Scale,
  film: Film,
  music: Music,
  headphones: Headphones,
  'gamepad-2': Gamepad2,
  dices: Dices,
  joystick: Joystick,
  drama: Drama,
  sticker: Sticker,
  'party-popper': PartyPopper,
  gift: Gift,
  ticket: Ticket,
  palette: Palette,
  camera: Camera,
  guitar: Guitar,
  trophy: Trophy,
  medal: Medal,
  volleyball: Volleyball,
  tent: Tent,
  'mountain-snow': MountainSnow,
  'tree-palm': TreePalm,
  sun: Sun,
  waves: Waves,
  umbrella: Umbrella,
  baby: Baby,
  'person-standing': PersonStanding,
  mars: Mars,
  venus: Venus,
  'users-round': UsersRound,
  'toy-brick': ToyBrick,
  blocks: Blocks,
  puzzle: Puzzle,
  'bed-single': BedSingle,
  'heart-handshake': HeartHandshake,
  heart: Heart,
  'hand-heart': HandHeart,
  'paw-print': PawPrint,
  dog: Dog,
  cat: Cat,
  bone: Bone,
  shirt: Shirt,
  scissors: Scissors,
  sparkles: Sparkles,
  'flower-2': Flower2,
  leaf: Leaf,
  sprout: Sprout,
  trees: Trees,
  church: Church,
  cigarette: Cigarette,
  smile: Smile,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'hand-coins': HandCoins,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'chart-line': ChartLine,
  'chart-pie': ChartPie,
  percent: Percent,
  calculator: Calculator,
  tag: Tag,
  tags: Tags,
  star: Star,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  lock: Lock,
  mail: Mail,
  send: Send,
  rocket: Rocket,
  target: Target,
  flag: Flag,
  bookmark: Bookmark,
  lightbulb: Lightbulb,
}

/** Nome em português de cada ícone: é o que aparece no seletor e no leitor de tela */
export const categoryIconLabels: Record<CategoryIconName, string> = {
  'shopping-cart': 'Carrinho de compras',
  'shopping-bag': 'Sacola',
  store: 'Loja',
  utensils: 'Talheres',
  'cooking-pot': 'Panela',
  salad: 'Salada',
  pizza: 'Pizza',
  sandwich: 'Lanche',
  drumstick: 'Frango',
  fish: 'Peixe',
  egg: 'Ovos',
  milk: 'Leite',
  apple: 'Fruta',
  carrot: 'Verdura',
  croissant: 'Padaria',
  'cake-slice': 'Bolo',
  candy: 'Doces',
  'ice-cream-cone': 'Sorvete',
  popcorn: 'Pipoca',
  coffee: 'Café',
  beer: 'Cerveja',
  wine: 'Vinho',
  house: 'Casa',
  bed: 'Cama',
  sofa: 'Sofá',
  armchair: 'Poltrona',
  lamp: 'Luminária',
  blinds: 'Cortina',
  bath: 'Banheira',
  'shower-head': 'Chuveiro',
  'washing-machine': 'Máquina de lavar',
  refrigerator: 'Geladeira',
  microwave: 'Micro-ondas',
  plug: 'Tomada',
  wrench: 'Chave inglesa',
  hammer: 'Martelo',
  'paint-roller': 'Pintura',
  key: 'Chave',
  'door-open': 'Porta',
  'trash-2': 'Lixo',
  package: 'Encomenda',
  zap: 'Energia',
  droplet: 'Água',
  flame: 'Gás',
  wifi: 'Internet',
  phone: 'Telefone',
  smartphone: 'Celular',
  router: 'Roteador',
  tv: 'TV',
  monitor: 'Computador',
  printer: 'Impressora',
  receipt: 'Boleto',
  'file-text': 'Documento',
  recycle: 'Reciclagem',
  shield: 'Seguro',
  cloud: 'Nuvem',
  globe: 'Mundo',
  car: 'Carro',
  'car-front': 'Carro de frente',
  'car-taxi-front': 'Táxi',
  fuel: 'Combustível',
  'circle-parking': 'Estacionamento',
  bus: 'Ônibus',
  'train-front': 'Trem',
  bike: 'Bicicleta',
  truck: 'Caminhão',
  plane: 'Avião',
  ship: 'Navio',
  luggage: 'Mala',
  'map-pin': 'Local',
  navigation: 'Navegação',
  footprints: 'Pegadas',
  'heart-pulse': 'Saúde',
  stethoscope: 'Consulta',
  pill: 'Remédio',
  syringe: 'Vacina',
  bandage: 'Curativo',
  hospital: 'Hospital',
  ambulance: 'Ambulância',
  cross: 'Farmácia',
  glasses: 'Óculos',
  brain: 'Terapia',
  accessibility: 'Acessibilidade',
  dumbbell: 'Academia',
  activity: 'Atividade',
  'graduation-cap': 'Educação',
  book: 'Livro',
  'book-open': 'Estudo',
  library: 'Biblioteca',
  school: 'Escola',
  backpack: 'Mochila',
  'bus-front': 'Ônibus escolar',
  'pencil-ruler': 'Material escolar',
  pencil: 'Lápis',
  ruler: 'Régua',
  briefcase: 'Trabalho',
  laptop: 'Notebook',
  presentation: 'Apresentação',
  'building-2': 'Empresa',
  users: 'Pessoas',
  'user-round': 'Pessoa',
  handshake: 'Acordo',
  'id-card': 'Documento pessoal',
  scale: 'Justiça',
  film: 'Cinema',
  music: 'Música',
  headphones: 'Fone',
  'gamepad-2': 'Games',
  dices: 'Jogos',
  joystick: 'Videogame',
  drama: 'Teatro',
  sticker: 'Adesivo',
  'party-popper': 'Festa',
  gift: 'Presente',
  ticket: 'Ingresso',
  palette: 'Arte',
  camera: 'Foto',
  guitar: 'Instrumento',
  trophy: 'Troféu',
  medal: 'Medalha',
  volleyball: 'Esporte',
  tent: 'Camping',
  'mountain-snow': 'Montanha',
  'tree-palm': 'Praia',
  sun: 'Sol',
  waves: 'Mar',
  umbrella: 'Guarda-chuva',
  baby: 'Bebê',
  'person-standing': 'Criança',
  mars: 'Menino',
  venus: 'Menina',
  'users-round': 'Família',
  'toy-brick': 'Brinquedo',
  blocks: 'Blocos',
  puzzle: 'Quebra-cabeça',
  'bed-single': 'Quarto de criança',
  'heart-handshake': 'Cuidado',
  heart: 'Coração',
  'hand-heart': 'Doação',
  'paw-print': 'Pet',
  dog: 'Cachorro',
  cat: 'Gato',
  bone: 'Ração',
  shirt: 'Roupa',
  scissors: 'Cabeleireiro',
  sparkles: 'Beleza',
  'flower-2': 'Flores',
  leaf: 'Planta',
  sprout: 'Muda',
  trees: 'Jardim',
  church: 'Igreja',
  cigarette: 'Cigarro',
  smile: 'Bem-estar',
  banknote: 'Dinheiro',
  coins: 'Moedas',
  wallet: 'Carteira',
  'credit-card': 'Cartão',
  'piggy-bank': 'Poupança',
  landmark: 'Banco',
  'hand-coins': 'Renda extra',
  'dollar-sign': 'Valor',
  'trending-up': 'Investimento',
  'trending-down': 'Queda',
  'chart-line': 'Gráfico',
  'chart-pie': 'Divisão',
  percent: 'Juros',
  calculator: 'Cálculo',
  tag: 'Etiqueta',
  tags: 'Etiquetas',
  star: 'Estrela',
  bell: 'Aviso',
  calendar: 'Data',
  clock: 'Tempo',
  lock: 'Segurança',
  mail: 'Correio',
  send: 'Envio',
  rocket: 'Meta',
  target: 'Objetivo',
  flag: 'Marco',
  bookmark: 'Marcador',
  lightbulb: 'Ideia',
}

/*
 * Palavras pelas quais se costuma procurar cada ícone, sem acento: "luz" acha Energia,
 * "uber" acha Táxi. É o que faz a busca servir para quem não pensa em inglês.
 */
const categoryIconKeywords: Record<CategoryIconName, string> = {
  'shopping-cart': 'mercado supermercado feira compras carrinho',
  'shopping-bag': 'compras mercado sacola bolsa',
  store: 'mercadinho comercio loja predio',
  utensils: 'restaurante almoco jantar comida garfo faca talher',
  'cooking-pot': 'cozinhar comida panela caldeirao',
  salad: 'almoco saudavel salada tigela',
  pizza: 'delivery pizza fatia',
  sandwich: 'lanchonete sanduiche',
  drumstick: 'carne acougue coxa frango carne',
  fish: 'peixaria peixe',
  egg: 'cafe da manha ovo',
  milk: 'laticinios leite caixinha',
  apple: 'feira hortifruti maca fruta',
  carrot: 'legumes feira cenoura',
  croissant: 'pao cafe da manha croissant pao',
  'cake-slice': 'doce aniversario confeitaria bolo fatia torta',
  candy: 'bala guloseima bala doce',
  'ice-cream-cone': 'gelato casquinha sorvete',
  popcorn: 'cinema pipoca balde',
  coffee: 'cafeteria xicara cafe',
  beer: 'bar boteco caneca chopp cerveja',
  wine: 'adega bar taca vinho',
  house: 'moradia aluguel lar casa telhado',
  bed: 'quarto dormir cama',
  sofa: 'sala moveis sofa',
  armchair: 'moveis poltrona cadeira',
  lamp: 'moveis decoracao luminaria abajur lampada',
  blinds: 'decoracao persiana cortina',
  bath: 'banheiro banheira',
  'shower-head': 'banho banheiro chuveiro ducha',
  'washing-machine': 'lavanderia roupa maquina de lavar',
  refrigerator: 'eletrodomestico geladeira freezer',
  microwave: 'eletrodomestico cozinha microondas forno',
  plug: 'eletrica eletrodomestico tomada plugue',
  wrench: 'conserto manutencao reforma chave inglesa ferramenta',
  hammer: 'reforma obra conserto martelo ferramenta',
  'paint-roller': 'reforma tinta rolo tinta pincel',
  key: 'aluguel imovel chave',
  'door-open': 'casa porta',
  'trash-2': 'limpeza descarte lixeira lata de lixo',
  package: 'entrega correios caixa pacote',
  zap: 'luz eletrica conta raio relampago',
  droplet: 'conta esgoto gota pingo',
  flame: 'botijao conta chama fogo fogueira',
  wifi: 'conta provedor wifi sinal',
  phone: 'conta fixo telefone fone',
  smartphone: 'conta plano celular telefone',
  router: 'internet roteador modem',
  tv: 'assinatura streaming televisao televisor',
  monitor: 'informatica monitor tela computador',
  printer: 'escritorio impressora',
  receipt: 'conta recibo recibo cupom nota fiscal comprovante',
  'file-text': 'papelada contrato arquivo folha papel',
  recycle: 'condominio limpeza reciclar simbolo',
  shield: 'protecao apolice escudo brasao',
  cloud: 'assinatura armazenamento nuvem',
  globe: 'site viagem internet globo planeta bola do mundo',
  car: 'automovel carro automovel',
  'car-front': 'automovel carro',
  'car-taxi-front': 'aplicativo corrida uber taxi carro',
  fuel: 'gasolina posto alcool bomba de gasolina posto',
  'circle-parking': 'vaga letra p estacionamento',
  bus: 'transporte publico passagem onibus',
  'train-front': 'metro transporte trem metro',
  bike: 'bike pedal bicicleta',
  truck: 'frete mudanca caminhao',
  plane: 'viagem passagem aerea aviao',
  ship: 'viagem cruzeiro navio barco',
  luggage: 'viagem bagagem mala bagagem',
  'map-pin': 'endereco pino mapa alfinete',
  navigation: 'gps rota seta bussola',
  footprints: 'caminhada pegadas pes',
  'heart-pulse': 'medico consulta coracao batimento eletro',
  stethoscope: 'medico clinica estetoscopio',
  pill: 'farmacia medicamento pilula comprimido capsula',
  syringe: 'injecao seringa agulha',
  bandage: 'machucado curativo band aid',
  hospital: 'internacao hospital predio',
  ambulance: 'emergencia ambulancia',
  cross: 'saude cruz',
  glasses: 'otica vista oculos',
  brain: 'psicologo mente cerebro',
  accessibility: 'cuidado cadeirante boneco',
  dumbbell: 'musculacao treino halter peso barra',
  activity: 'exercicio batimento pulso onda batimento',
  'graduation-cap': 'escola faculdade formatura capelo chapeu formatura',
  book: 'leitura estudo livro',
  'book-open': 'curso apostila livro aberto',
  library: 'estudo livros estante livros',
  school: 'colegio filho aula escola predio',
  backpack: 'escola filho material mochila',
  'bus-front': 'transporte escola filho onibus',
  'pencil-ruler': 'papelaria caderno lapis regua',
  pencil: 'papelaria escrever lapis',
  ruler: 'papelaria medida regua',
  briefcase: 'emprego negocio maleta pasta',
  laptop: 'trabalho informatica notebook computador',
  presentation: 'reuniao curso quadro tela',
  'building-2': 'escritorio predio predio edificio',
  users: 'equipe familia amigos pessoas grupo',
  'user-round': 'alguem contato pessoa perfil',
  handshake: 'sociedade negocio aperto de mao maos',
  'id-card': 'rg cnh identidade cracha carteirinha',
  scale: 'advogado processo imposto balanca',
  film: 'filme streaming filme rolo claquete',
  music: 'show streaming nota musical',
  headphones: 'musica podcast fone de ouvido',
  'gamepad-2': 'jogo videogame controle joystick',
  dices: 'tabuleiro sorte dados',
  joystick: 'jogo controle controle alavanca',
  drama: 'peca cultura mascaras teatro',
  sticker: 'diversao adesivo selo',
  'party-popper': 'comemoracao aniversario confete festa',
  gift: 'aniversario natal presente caixa laco',
  ticket: 'show evento ingresso bilhete',
  palette: 'hobby pintura paleta tinta',
  camera: 'fotografia camera maquina fotografica',
  guitar: 'musica violao violao guitarra',
  trophy: 'meta conquista trofeu taca premio',
  medal: 'conquista medalha',
  volleyball: 'jogo bola bola',
  tent: 'acampamento viagem barraca',
  'mountain-snow': 'viagem trilha montanha',
  'tree-palm': 'ferias viagem coqueiro palmeira',
  sun: 'verao ferias sol',
  waves: 'praia piscina ondas',
  umbrella: 'chuva praia guarda chuva sombrinha',
  baby: 'filho fralda crianca nenem bebe nenem crianca',
  'person-standing': 'filho filha menino menina crianca boneco pessoa',
  mars: 'filho garoto masculino simbolo masculino',
  venus: 'filha garota feminino simbolo feminino',
  'users-round': 'casal filhos todos pessoas grupo',
  'toy-brick': 'crianca filho presente peca lego bloco',
  blocks: 'brinquedo crianca blocos pecas',
  puzzle: 'brinquedo jogo crianca quebra cabeca peca',
  'bed-single': 'cama filho cama de solteiro',
  'heart-handshake': 'ajuda apoio pensao maos coracao',
  heart: 'amor doacao coracao',
  'hand-heart': 'caridade ajuda mao coracao',
  'paw-print': 'animal bicho patinha pata',
  dog: 'pet cachorro cao',
  cat: 'pet gato',
  bone: 'pet osso osso',
  shirt: 'vestuario camisa camiseta',
  scissors: 'salao barbeiro corte tesoura',
  sparkles: 'estetica cuidados brilhos estrelinhas',
  'flower-2': 'presente jardim flor',
  leaf: 'jardim natureza folha',
  sprout: 'jardinagem broto mudinha',
  trees: 'plantas quintal arvores arvore',
  church: 'dizimo religiao igreja capela',
  cigarette: 'tabaco cigarro',
  smile: 'sorriso carinha sorriso',
  banknote: 'salario nota cedula nota dinheiro',
  coins: 'troco economia moedas',
  wallet: 'dinheiro carteira',
  'credit-card': 'credito debito fatura cartao',
  'piggy-bank': 'guardar reserva cofrinho porquinho',
  landmark: 'instituicao imposto predio colunas banco',
  'hand-coins': 'bico pagamento mao moedas',
  'dollar-sign': 'dinheiro cifrao simbolo',
  'trending-up': 'alta rendimento seta subindo',
  'trending-down': 'perda seta descendo',
  'chart-line': 'investimento analise grafico linha',
  'chart-pie': 'proporcao relatorio grafico pizza',
  percent: 'desconto taxa porcentagem',
  calculator: 'contas imposto calculadora',
  tag: 'geral categoria etiqueta',
  tags: 'categorias etiquetas',
  star: 'favorito estrela',
  bell: 'lembrete sino campainha',
  calendar: 'agenda mensal calendario',
  clock: 'hora prazo relogio',
  lock: 'cofre senha cadeado tranca trancado',
  mail: 'carta envelope carta email',
  send: 'transferencia enviar aviao de papel',
  rocket: 'projeto comeco foguete',
  target: 'meta alvo alvo mira',
  flag: 'meta bandeira bandeira',
  bookmark: 'guardar marcador favorito',
  lightbulb: 'projeto lampada ideia',
}

/** Os ícones em famílias, como numa gaveta organizada: é assim que se procura */
export const categoryIconGroups: { label: string; icons: CategoryIconName[] }[] = [
  {
    label: 'Alimentação',
    icons: [
      'shopping-cart',
      'shopping-bag',
      'store',
      'utensils',
      'cooking-pot',
      'salad',
      'pizza',
      'sandwich',
      'drumstick',
      'fish',
      'egg',
      'milk',
      'apple',
      'carrot',
      'croissant',
      'cake-slice',
      'candy',
      'ice-cream-cone',
      'popcorn',
      'coffee',
      'beer',
      'wine',
    ],
  },
  {
    label: 'Casa',
    icons: [
      'house',
      'bed',
      'sofa',
      'armchair',
      'lamp',
      'blinds',
      'bath',
      'shower-head',
      'washing-machine',
      'refrigerator',
      'microwave',
      'plug',
      'wrench',
      'hammer',
      'paint-roller',
      'key',
      'door-open',
      'trash-2',
      'package',
    ],
  },
  {
    label: 'Contas e serviços',
    icons: [
      'zap',
      'droplet',
      'flame',
      'wifi',
      'phone',
      'smartphone',
      'router',
      'tv',
      'monitor',
      'printer',
      'receipt',
      'file-text',
      'recycle',
      'shield',
      'cloud',
      'globe',
    ],
  },
  {
    label: 'Transporte',
    icons: [
      'car',
      'car-front',
      'car-taxi-front',
      'fuel',
      'circle-parking',
      'bus',
      'train-front',
      'bike',
      'truck',
      'plane',
      'ship',
      'luggage',
      'map-pin',
      'navigation',
      'footprints',
    ],
  },
  {
    label: 'Saúde',
    icons: [
      'heart-pulse',
      'stethoscope',
      'pill',
      'syringe',
      'bandage',
      'hospital',
      'ambulance',
      'cross',
      'glasses',
      'brain',
      'accessibility',
      'dumbbell',
      'activity',
    ],
  },
  {
    label: 'Educação e trabalho',
    icons: [
      'graduation-cap',
      'book',
      'book-open',
      'library',
      'school',
      'backpack',
      'bus-front',
      'pencil-ruler',
      'pencil',
      'ruler',
      'briefcase',
      'laptop',
      'presentation',
      'building-2',
      'users',
      'user-round',
      'handshake',
      'id-card',
      'scale',
    ],
  },
  {
    label: 'Lazer',
    icons: [
      'film',
      'music',
      'headphones',
      'gamepad-2',
      'dices',
      'joystick',
      'drama',
      'sticker',
      'party-popper',
      'gift',
      'ticket',
      'palette',
      'camera',
      'guitar',
      'trophy',
      'medal',
      'volleyball',
      'tent',
      'mountain-snow',
      'tree-palm',
      'sun',
      'waves',
      'umbrella',
    ],
  },
  {
    label: 'Família e pets',
    icons: [
      'baby',
      'person-standing',
      'mars',
      'venus',
      'users-round',
      'toy-brick',
      'blocks',
      'puzzle',
      'bed-single',
      'heart-handshake',
      'heart',
      'hand-heart',
      'paw-print',
      'dog',
      'cat',
      'bone',
      'shirt',
      'scissors',
      'sparkles',
      'flower-2',
      'leaf',
      'sprout',
      'trees',
      'church',
      'cigarette',
      'smile',
    ],
  },
  {
    label: 'Dinheiro',
    icons: [
      'banknote',
      'coins',
      'wallet',
      'credit-card',
      'piggy-bank',
      'landmark',
      'hand-coins',
      'dollar-sign',
      'trending-up',
      'trending-down',
      'chart-line',
      'chart-pie',
      'percent',
      'calculator',
    ],
  },
  {
    label: 'Outros',
    icons: [
      'tag',
      'tags',
      'star',
      'bell',
      'calendar',
      'clock',
      'lock',
      'mail',
      'send',
      'rocket',
      'target',
      'flag',
      'bookmark',
      'lightbulb',
    ],
  },
]

/** Tudo o que serve para achar um ícone: o rótulo, as palavras e o nome em inglês */
export const iconSearchText = (name: CategoryIconName) =>
  `${categoryIconLabels[name]} ${categoryIconKeywords[name]} ${name.replace(/-/g, ' ')}`
