import type { CategoryIconName } from '@bolso/shared'
import {
  Baby,
  Banknote,
  Briefcase,
  Car,
  Droplet,
  Dumbbell,
  Film,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  type LucideIcon,
  PartyPopper,
  PawPrint,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingCart,
  Smartphone,
  Tag,
  TrendingUp,
  Utensils,
  Wifi,
  Zap,
} from 'lucide-react'

// O tipo Record obriga a ter um ícone para cada nome listado em schema.ts
export const categoryIcons: Record<CategoryIconName, LucideIcon> = {
  'shopping-cart': ShoppingCart,
  utensils: Utensils,
  house: House,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  car: Car,
  plane: Plane,
  'heart-pulse': HeartPulse,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  baby: Baby,
  'paw-print': PawPrint,
  shirt: Shirt,
  smartphone: Smartphone,
  film: Film,
  'party-popper': PartyPopper,
  gift: Gift,
  receipt: Receipt,
  tag: Tag,
  briefcase: Briefcase,
  banknote: Banknote,
  'trending-up': TrendingUp,
  'piggy-bank': PiggyBank,
}
